// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv-Kg5jb9M6jsINS3jLA55shoAXkUCbjY',
    appId: '1:749238580298:web:7b0dd93ec33ff362c6e2b3',
    messagingSenderId: '749238580298',
    projectId: 'flutterhimnavi',
    authDomain: 'flutterhimnavi.firebaseapp.com',
    storageBucket: 'flutterhimnavi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKPYZdoTx6j_6dVZu1MwtTt1Kzfr9h668',
    appId: '1:749238580298:android:3614af2d64818145c6e2b3',
    messagingSenderId: '749238580298',
    projectId: 'flutterhimnavi',
    storageBucket: 'flutterhimnavi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-fP3HmB9ywkO61S7WmZar1FrXKCRhbdk',
    appId: '1:749238580298:ios:10b9548fe9446509c6e2b3',
    messagingSenderId: '749238580298',
    projectId: 'flutterhimnavi',
    storageBucket: 'flutterhimnavi.appspot.com',
    iosClientId: '749238580298-5di3vsn9jktikduscfakccqoo9k3j5k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.himiNaviRec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-fP3HmB9ywkO61S7WmZar1FrXKCRhbdk',
    appId: '1:749238580298:ios:64d21cb888782128c6e2b3',
    messagingSenderId: '749238580298',
    projectId: 'flutterhimnavi',
    storageBucket: 'flutterhimnavi.appspot.com',
    iosClientId: '749238580298-77fnn6arjte3288ae43b7ue4noiqup7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.himiNaviRec.RunnerTests',
  );
}
